#공통 설정
resource:
  temp-resource:
    #임시 자원 유효 시간(분)
    effective-minute: ${TEMP_RESOURCE_EFFECTIVE_MINUTE}
    batch:
      #임시 자원 삭제 스케쥴러 고정 레이트(ms)
      clear-scheduler-cron: ${TEMP_RESOURCE_CLEAR_SCHEDULER_CRON}
      #임시 자원 삭제 배치 job name
      clear-job-name: CLEAR_TEMP_RESOURCE
      #임시 자원 삭제 배치 step name
      clear-step-name: CLEAR_TEMP_RESOURCE
      #임시 자원 삭제 배치 chunk size
      clear-chunk-size: 10
---
#local resource upload server 설정
spring:
  config:
    activate:
      on-profile: 'upload-local'
  upload:
    resource_host: ${RESOURCE_HOST}
    upload_root: ${UPLOAD_ROOT}
    urlPath: /upload/
---
spring:
  config:
    activate:
      on-profile: 'upload-aws_s3'
cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET_NAME}
    credentials:
      access-key: ${AWS_S3_ACCESS_KEY}
      secret-key: ${AWS_S3_SECRET_KEY}
    region:
      static: ${AWS_S3_REGION}
      auto: false
    stack:
      auto: false